defaults:
  - sdpcodec_hubert_rvq6561
  - _self_

model:
  duration_codec:
    enabled: true
    run_slug: durfree/flexi/dynthr085-100/evalthr090/localattn16/maxspan16/gtdur
    token_merge_type: flexicodec
    duration_injection: false
    use_duration_predictor: false
    boundary_feature_source: content
    boundary_mode: cosine_threshold
    boundary_cosine_threshold: 0.90
    boundary_dynamic_threshold: true
    boundary_dynamic_threshold_lower: 0.85
    boundary_dynamic_threshold_upper: 1.0
    boundary_dynamic_threshold_eval: false
    min_segment_frames: 1
    max_segment_frames: 16
    max_duration_frames: 16
    local_attention_enabled: true
    local_attention_window: 16
    local_attention_heads: 8
    local_attention_layers: 1
    local_attention_dropout: 0.0
    local_attention_ffn_mult: 4.0
    mask_fill_enabled: true
    local_unmerge_attention_enabled: true
    local_unmerge_attention_window: 16
    local_unmerge_attention_heads: 8
    local_unmerge_attention_layers: 1
    local_unmerge_attention_dropout: 0.0
    local_unmerge_attention_ffn_mult: 4.0

train:
  wandb_project: BigCodec
  wandb_name: sddpcodec/hubert/MLS+LS/25Hz/rvq6561/nearbyrefclip/b4ddp2acc2/train6s/val6s/durfree/flexi/dynthr085-100/evalthr090/localattn16/maxspan16/gtdur
